services:

  mysql:
    image: mysql:8.4
    container_name: securescan-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: securescan
      MYSQL_USER: securescan
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: ./securescan
      dockerfile: Dockerfile

    container_name: securescan-backend
    restart: unless-stopped

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/securescan?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: securescan
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

      FRONTEND_URL: ${FRONTEND_URL}
      JWT_SECRET: ${JWT_SECRET}

    depends_on:
      mysql:
        condition: service_healthy


  caddy:
    image: caddy:2-alpine
    container_name: securescan-caddy
    restart: unless-stopped

    environment:
      BACKEND_HOSTNAME: ${BACKEND_HOSTNAME}

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

    depends_on:
      - backend


volumes:
  mysql_data:
  caddy_data:
  caddy_config: